[package]
name = "gc_machine"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.10.0"
rand_chacha = "0.10.0"
sha2 = "0.10.9"
criterion = "0.3"
stats_alloc = "0.1.10"

[[bench]]
name = "bench_example"
harness = false

