[package]
name = "gc_machine"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
sha2 = "0.10.9"
criterion = "0.3"
stats_alloc = "0.1.10"
glass_pumpkin = "1.10.0"
k256 = "0.13.4"

[[bench]]
name = "bench"
harness = false

glass_pumpkin = "1.0"
